/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ao.sga.login;

import ao.sga.janela.init.Main;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import ao.sga.modelo.*;
/**
 *
 * @author man-tung
 */
public class LoginProf extends javax.swing.JFrame {
    

    /**
     * Creates new form LoginProf
     */
    public LoginProf() {
        initComponents();
    }
    
/*    public LoginProf(ArrayList<Turma> turmas) {
        this.turmas = turmas;
        System.out.println(" AQUIIIII");
        initComponents();
    }
*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        usernameProf = new javax.swing.JTextField();
        passwordProf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loginProf = new javax.swing.JButton();
        btnInitProf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Impact", 1, 17)); // NOI18N
        jLabel2.setText("Usernane");

        usernameProf.setBackground(new java.awt.Color(255, 255, 255));
        usernameProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameProfActionPerformed(evt);
            }
        });

        passwordProf.setBackground(new java.awt.Color(255, 255, 255));
        passwordProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordProfActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Impact", 1, 17)); // NOI18N
        jLabel3.setText("Password");

        loginProf.setBackground(new java.awt.Color(0, 51, 255));
        loginProf.setFont(new java.awt.Font("Impact", 1, 17)); // NOI18N
        loginProf.setText("Login");
        loginProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginProfActionPerformed(evt);
            }
        });

        btnInitProf.setBackground(new java.awt.Color(0, 51, 255));
        btnInitProf.setFont(new java.awt.Font("Impact", 1, 17)); // NOI18N
        btnInitProf.setText("Inicio");
        btnInitProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitProfActionPerformed(evt);
            }
        });

        jLabel1.setText("Login como Professor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(usernameProf, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordProf, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(loginProf)
                    .addComponent(btnInitProf))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginProf)
                .addGap(18, 18, 18)
                .addComponent(btnInitProf)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameProfActionPerformed

    private void passwordProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordProfActionPerformed

    
    private void loginProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginProfActionPerformed
           // TODO add your handling code here:
           /*if (turmas == null)
               return ;
           ArrayList<Prof> profs = new ArrayList<>();
           for (Turma t : turmas) {
                profs.addAll(t.getProf());
            }
             */
            ArrayList<Prof> profs = new ArrayList<Prof>();
            profs.add(new Prof("SandroC", "01/05/1987", "sandroC", "125"));
            profs.add(new Prof("SandroC", "01/05/1987", "sandroB", "124"));
            profs.add(new Prof("SandroC", "01/05/1987", "sandroA", "123"));

          // int rs = loginUtilProf(usernameProf, passwordProf, profs);
          // if (rs == 1)
              JOptionPane.showMessageDialog(rootPane, "NAO LOGADO!");

    }//GEN-LAST:event_loginProfActionPerformed

    private void btnInitProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitProfActionPerformed
        Main init = new Main();
        init.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_btnInitProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginProf().setVisible(true);
            }
        });
    }

    
      ArrayList<Turma> turmas = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInitProf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginProf;
    private javax.swing.JTextField passwordProf;
    private javax.swing.JTextField usernameProf;
    // End of variables declaration//GEN-END:variables
}
