/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ao.sga.janela.init;

import ao.sga.modelo.Admin;
import ao.sga.modelo.Aluno;
import ao.sga.modelo.Disc;
import ao.sga.modelo.Prof;
import ao.sga.modelo.RendEscola;
import ao.sga.modelo.Turma;





import ao.sga.login.LoginAdmin;
import ao.sga.login.LoginAluno;
import ao.sga.login.LoginProf;
import ao.sga.login.LoginProfessor;
import java.util.ArrayList;

/**
 *
 * @author man-tung
 */
public class Main extends javax.swing.JFrame {

    
     Prof profAdmin = null;
     ArrayList<Aluno> alunos = null;
     ArrayList<Turma> turmas = null;
     ArrayList<Disc> discs = null;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
         initVars();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tela inicial");

        jButton1.setText("Logar como Professor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Logar como Admin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Logar como Aluno");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addGap(0, 154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (turmas != null)
        {
            LoginProfessor telaLoginProf = new LoginProfessor(turmas);
            telaLoginProf.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginAdmin telaLoginAdmin = new LoginAdmin(turmas, this);
        telaLoginAdmin.setVisible(true);
        this.setVisible(false);
//this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LoginAluno telaLoginAluno = new LoginAluno();
        telaLoginAluno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void initVars()
    {
        alunos = new ArrayList<Aluno>();
        turmas = new ArrayList<Turma>();
        discs = new ArrayList<Disc>();
        
        Turma turmaNew = new Turma(30, "A");
        Turma turmaNew1 = new Turma(30, "B");
        Turma turmaNew2 = new Turma(30, "C");

        
        Disc discNew = new Disc("Aritme'tica", "Emenda o que e' isso?");
        Disc discNew1 = new Disc("Aritme'tica1", "Emenda o que e' isso?");
        Disc discNew2 = new Disc("Aritme'tica2", "Emenda o que e' isso?");
        Disc discNew3 = new Disc("Aritme'tica3", "Emenda o que e' isso?");
        Disc discNew4 = new Disc("Aritme'tica4", "Emenda o que e' isso?");
        Disc discNew5 = new Disc("Aritme'tica5", "Emenda o que e' isso?");

        
        Prof profNew = new Prof("SandroA", "01/03/1987", "sandroa", "123");
        discNew.AddProf(profNew);discNew1.AddProf(profNew);
        turmaNew.AddProf(profNew);
        turmas.add(turmaNew);
        
        Prof profNew1 = new Prof("SandroB", "01/04/1987", "sandrob", "124");
        discNew2.AddProf(profNew1);discNew3.AddProf(profNew1);
        turmaNew1.AddProf(profNew1);
        turmas.add(turmaNew1);

        Prof profNew2 = new Prof("SandroC", "01/05/1987", "sandroC", "125");
        discNew4.AddProf(profNew2);discNew5.AddProf(profNew2);
        turmaNew2.AddProf(profNew2);
        turmas.add(turmaNew2);
        
      


        //Turma new
        Aluno alunoNew = new Aluno("Sandro", "Aluno", "01|04|1987", "sandro@gmail.com", "123");
        turmaNew.AddAluno(alunoNew);
        
        Aluno alunoNew1 = new Aluno("Sandro1", "Aluno", "01|04|1987", "sandro@gmail.com", "123");
        turmaNew.AddAluno(alunoNew1);
        
        Aluno alunoNew2 = new Aluno("Sandro2", "Aluno", "01|04|1987", "sandro@gmail.com", "123");
        turmaNew.AddAluno(alunoNew2);
        
        
        //Turma new1
        Aluno alunoNew3 = new Aluno("Sandro3", "Aluno", "01|04|1987", "sandro@gmail.com", "123");
        turmaNew1.AddAluno(alunoNew3);

        Aluno alunoNew4 = new Aluno("Sandro4", "Aluno", "01|04|1987", "sandro@gmail.com", "123");
        turmaNew1.AddAluno(alunoNew4);

        Aluno alunoNew5 = new Aluno("Sandro5", "Aluno", "01|04|1987", "sandro@gmail.com", "123");
        turmaNew1.AddAluno(alunoNew5);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
