/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ao.sga.janela.caadastro;

import ao.sga.dashboard.DashboardAdmin;
import ao.sga.janela.init.Main;
import ao.sga.modelo.Turma;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author man-tung
 */
public class CadastroTurma extends javax.swing.JFrame {
            ArrayList<Turma> turmas = null;
            private DefaultListModel<String> modelList = null;
            JFrame janela = null;


    /**
     * Creates new form CadastroTurma
     */
    public CadastroTurma() {
        initComponents();
    }
    public CadastroTurma(ArrayList<Turma> turmas, JFrame janela) {
        initComponents();
        this.turmas = turmas;
        this.janela = janela;
        modelList = new DefaultListModel<>();
        listaTurma.setModel(modelList);
        popularListaTurma();    
    }
    
    private void popularListaTurma()
    {
        modelList.clear();
        turmas.forEach((t) -> {
            modelList.addElement("CAP: "+t.getCap()+" TURMA: "+t.getName());
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeTurma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        capTurma = new javax.swing.JTextField();
        btnGuardarTurma = new javax.swing.JButton();
        btnCadastroVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTurma = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadastrar Turma");

        nomeTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTurmaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel3.setText("Cap");

        capTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capTurmaActionPerformed(evt);
            }
        });

        btnGuardarTurma.setText("Guardar");
        btnGuardarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTurmaActionPerformed(evt);
            }
        });

        btnCadastroVoltar.setText("Sair");
        btnCadastroVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroVoltarActionPerformed(evt);
            }
        });

        listaTurma.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaTurma);

        jLabel4.setText("Cadastrar Turma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnCadastroVoltar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(nomeTurma)
                        .addComponent(jLabel3)
                        .addComponent(capTurma)
                        .addComponent(btnGuardarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 184, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(capTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadastroVoltar))
                    .addComponent(jScrollPane1))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTurmaActionPerformed

    private void capTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capTurmaActionPerformed

    private void btnGuardarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTurmaActionPerformed
        // TODO add your handling code here:
        int cap = 0;
        try {
            cap = Integer.parseInt(capTurma.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Entrada inva'lida!");
            return ;
        }

        if (!nomeTurma.getText().isEmpty() && !capTurma.getText().isEmpty())
        {
            turmas.add(new Turma(cap, nomeTurma.getText()));
            popularListaTurma();
            nomeTurma.setText("");
            capTurma.setText("");
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Entrada inva'lida!");
    }//GEN-LAST:event_btnGuardarTurmaActionPerformed

    private void btnCadastroVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroVoltarActionPerformed
        // TODO add your handling code here:
        //Main telaInit = new Main();
        janela.setVisible(true);
        this.dispose();
                     
    }//GEN-LAST:event_btnCadastroVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTurma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroVoltar;
    private javax.swing.JButton btnGuardarTurma;
    private javax.swing.JTextField capTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaTurma;
    private javax.swing.JTextField nomeTurma;
    // End of variables declaration//GEN-END:variables
}
