/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ao.sga.janela.caadastro;

import ao.sga.modelo.Aluno;
import ao.sga.modelo.Disc;
import ao.sga.modelo.Prof;
import ao.sga.modelo.Turma;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author man-tung
 */
public class CadastroNota extends javax.swing.JFrame {

    
        ArrayList<Turma> turmas = null;
        ArrayList<Aluno> alunos = null;
        Aluno alunoSeleted = null;
        Disc disciplina = null;
        Prof prof = null;
        JFrame janela = null;
         private DefaultListModel<String> modelList = null;

    /**
     * Creates new form CadastroNota
     */
    public CadastroNota() {
        initComponents();
    }

    public CadastroNota(ArrayList<Turma> turmas, JFrame janela, Prof prof) {
        initComponents();
        this.janela = janela;
        this.turmas = turmas;
        this.prof = prof;
        System.out.println(">>>>> PROFESSOR: "+prof.getName());
        comboboxTurmasCadastroNota.removeAllItems();
        comboboxDisciplinsCadastroNota.removeAllItems();
        comboboxAlunosCadastroNota.removeAllItems();
        
        //popular as turmas
        prof.getTurma().forEach((t) -> {
               comboboxTurmasCadastroNota.addItem(t.getName());
        });
        
        
        //alterei a turma populo as disciplinas e os alunos
        comboboxTurmasCadastroNota.addActionListener((ae) -> { 
    
             comboboxDisciplinsCadastroNota.removeAllItems();
            //Disciplinas que o prof leciona nesta turma
            prof.getTurma().get(comboboxTurmasCadastroNota.getSelectedIndex()).getDisc().forEach((d) -> {
                if (prof.getDisc().contains(d))
                     comboboxDisciplinsCadastroNota.addItem(d.getName());
            });
            comboboxAlunosCadastroNota.removeAllItems();
            //Alunos nesta Turma
            prof.getTurma().get(comboboxTurmasCadastroNota.getSelectedIndex()).getAluno().forEach((a) -> {
                comboboxAlunosCadastroNota.addItem(a.getName());                
            });
        });        
        
        //Seleciona Disciplina
        comboboxDisciplinsCadastroNota.addActionListener((ae) -> {
            popularListaAlunosMedias();
        });
        
        //Selecionei o alunos
        comboboxAlunosCadastroNota.addActionListener((ae) -> { 
            alunoSeleted = prof.getTurma()
                    .get(comboboxTurmasCadastroNota.getSelectedIndex())
                    .getAluno()
                    .get(comboboxAlunosCadastroNota.getSelectedIndex() < 0 ? 0 : comboboxAlunosCadastroNota.getSelectedIndex());
            System.out.println("ALUNO SELECIONADO EE: "+(alunoSeleted != null ? alunoSeleted.getName() : "Aluno desconhecido"));
        });
        
        modelList = new DefaultListModel<>();
        listaAlunosMediaCadastroNota.setModel(modelList);
        modelList.clear();

//        popularListaAlunoMedia(); 
    }  
    
    private void popularListaAlunosMedias()
    {
        System.err.println(">>> popularListaAlunosMedias()");
        //modelList.clear();
        //disciplina
        prof.getDisc()
                .get(comboboxDisciplinsCadastroNota.getSelectedIndex() < 0 ? 0 : comboboxDisciplinsCadastroNota.getSelectedIndex())
                .getAluno().forEach((a) -> {
                    if (a == null)
                        return ;
                    a.discs.forEach((d) -> {
                    if (d.getName().equals(prof.getDisc().get(comboboxDisciplinsCadastroNota.getSelectedIndex()).getName()))
                    {
                        modelList.addElement("Aluno: "+a.getName()+" | Disciplina: "+d.getName()+" | Me'dia: "+d.getMedia());
                    }
            }); 
        });
    }
    
    private void popularListaAlunoMedia()
    {
        //modelList.clear();
       selectedElements();//seleciona alunos e disciplinas
       
        if (alunoSeleted == null)
            return ;
        alunoSeleted.discs.forEach((d) -> {
            if (d.getName().equals(disciplina.getName()))
            {
                modelList.addElement("Aluno: "+alunoSeleted.getName()+" | Disciplina: "+disciplina.getName()+" | Me'dia: "+disciplina.getMedia());
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboboxTurmasCadastroNota = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnGuardarCadastroNota = new javax.swing.JButton();
        btnSairCadastroNota = new javax.swing.JButton();
        comboboxDisciplinsCadastroNota = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        comboboxAlunosCadastroNota = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nota3CadastroNota = new javax.swing.JTextField();
        nota1CadastroNota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nota2CadastroNota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mediaAlunoSelecionado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAlunosMediaCadastroNota = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboboxTurmasCadastroNota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Disciplina");

        jLabel1.setText("Cadastro de Notas");

        btnGuardarCadastroNota.setText("Guardar");
        btnGuardarCadastroNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCadastroNotaActionPerformed(evt);
            }
        });

        btnSairCadastroNota.setText("Sair");
        btnSairCadastroNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastroNotaActionPerformed(evt);
            }
        });

        comboboxDisciplinsCadastroNota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Turma");

        comboboxAlunosCadastroNota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Aluno");

        jLabel3.setText("Exame");

        nota3CadastroNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nota3CadastroNotaActionPerformed(evt);
            }
        });

        nota1CadastroNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nota1CadastroNotaActionPerformed(evt);
            }
        });

        jLabel4.setText("Nota 1");

        nota2CadastroNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nota2CadastroNotaActionPerformed(evt);
            }
        });

        jLabel7.setText("Nota 2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel1)
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(nota1CadastroNota, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(nota2CadastroNota, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(nota3CadastroNota, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSairCadastroNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardarCadastroNota, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboboxTurmasCadastroNota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboboxDisciplinsCadastroNota, 0, 388, Short.MAX_VALUE)
                    .addComponent(comboboxAlunosCadastroNota, 0, 388, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mediaAlunoSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nota3CadastroNota, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboboxTurmasCadastroNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nota2CadastroNota, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nota1CadastroNota, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxDisciplinsCadastroNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxAlunosCadastroNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardarCadastroNota, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSairCadastroNota)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mediaAlunoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        listaAlunosMediaCadastroNota.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaAlunosMediaCadastroNota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nota3CadastroNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nota3CadastroNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nota3CadastroNotaActionPerformed

    private void btnSairCadastroNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastroNotaActionPerformed
        janela.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairCadastroNotaActionPerformed

    private void selectedElements()
    {
        alunoSeleted = prof.getTurma().get(comboboxTurmasCadastroNota.getSelectedIndex()).getAluno().get(comboboxAlunosCadastroNota.getSelectedIndex());
            if (alunoSeleted == null)
                return ;
            
            alunoSeleted.discs.forEach((d) -> {
                if (d.getName().equals(prof.getDisc().get(comboboxDisciplinsCadastroNota.getSelectedIndex()).getName()))
                {
                    disciplina = d;
                }
            });
    }
    private void btnGuardarCadastroNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCadastroNotaActionPerformed

        
        if (!nota1CadastroNota.getText().isEmpty() &&
            !nota2CadastroNota.getText().isEmpty() &&
            !nota3CadastroNota.getText().isEmpty())
        {
            //verificar se 'e numero
            double n1 = Double.parseDouble(nota1CadastroNota.getText());
            double n2 = Double.parseDouble(nota2CadastroNota.getText());
            double n3 = Double.parseDouble(nota3CadastroNota.getText());

           
            selectedElements();//seta o alunoSelected pelo aluno selecionado
            
            if (disciplina == null)
                return ;
            disciplina.setN1(n1);
            disciplina.setN2(n2);
            disciplina.setN3(n3);
            
            mediaAlunoSelecionado.setText(Double.toString(disciplina.getMedia()));
            popularListaAlunoMedia();
            
            
         /*   aluno.
            Turma turma = turmas.get(comboboxTurmasCadastroNota.getSelectedIndex());
            Disc d = turma.getDisc().get(comboboxDisciplinsCadastroNota.getSelectedIndex());
            d.AddProf(new Prof(nomeCadastroProf.getText(), dataCadastroProf.getText(), userNameCadastroProf.getText(), passwordCadastroProf.getText()));
            passwordCadastroProf.setText("");
            nomeCadastroProf.setText("");
            userNameCadastroProf.setText("");
            dataCadastroProf.setText("");*/
        }
    }//GEN-LAST:event_btnGuardarCadastroNotaActionPerformed

    private void nota1CadastroNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nota1CadastroNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nota1CadastroNotaActionPerformed

    private void nota2CadastroNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nota2CadastroNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nota2CadastroNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCadastroNota;
    private javax.swing.JButton btnSairCadastroNota;
    private javax.swing.JComboBox<String> comboboxAlunosCadastroNota;
    private javax.swing.JComboBox<String> comboboxDisciplinsCadastroNota;
    private javax.swing.JComboBox<String> comboboxTurmasCadastroNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaAlunosMediaCadastroNota;
    private javax.swing.JLabel mediaAlunoSelecionado;
    private javax.swing.JTextField nota1CadastroNota;
    private javax.swing.JTextField nota2CadastroNota;
    private javax.swing.JTextField nota3CadastroNota;
    // End of variables declaration//GEN-END:variables
}
