/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ao.sga.janela.caadastro;

import ao.sga.modelo.Disc;
import ao.sga.modelo.Prof;
import ao.sga.modelo.Turma;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author man-tung
 */
public class CadastroProf extends javax.swing.JFrame {

            ArrayList<Turma> turmas = null;
            JFrame janela = null;
    /**
     * Creates new form CadastroProf
     */
    public CadastroProf() {
        initComponents();
    }
    
    public CadastroProf(ArrayList<Turma> turmas, JFrame janela) {
        initComponents();
        this.janela = janela;
        this.turmas = turmas;
        
        comboboxTurmasCadastroProf.removeAllItems();
        turmas.forEach((t) -> {
            comboboxTurmasCadastroProf.addItem(t.getName());
        });
        
        comboboxTurmasCadastroProf.addActionListener((ae) -> {
            popularListaAluno(comboboxTurmasCadastroProf.getSelectedIndex());
        });
    }
    
    private void popularListaAluno(int index)
    {
        comboboxDisciplinssCadastroProf.removeAllItems();
        turmas.get(index).getDisc().forEach((t) -> {
            comboboxDisciplinssCadastroProf.addItem(t.getName());
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboboxTurmasCadastroProf = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeCadastroProf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userNameCadastroProf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordCadastroProf = new javax.swing.JTextField();
        btnGuardarCadastroProf = new javax.swing.JButton();
        btnSairCadastroProf = new javax.swing.JButton();
        comboboxDisciplinssCadastroProf = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dataCadastroProf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboboxTurmasCadastroProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Disciplina");

        jLabel1.setText("Cadastro de Professores");

        jLabel2.setText("Nome");

        nomeCadastroProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCadastroProfActionPerformed(evt);
            }
        });

        jLabel3.setText("Username");

        userNameCadastroProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameCadastroProfActionPerformed(evt);
            }
        });

        jLabel4.setText("Password");

        passwordCadastroProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordCadastroProfActionPerformed(evt);
            }
        });

        btnGuardarCadastroProf.setText("Guardar");
        btnGuardarCadastroProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCadastroProfActionPerformed(evt);
            }
        });

        btnSairCadastroProf.setText("Sair");
        btnSairCadastroProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastroProfActionPerformed(evt);
            }
        });

        comboboxDisciplinssCadastroProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Turma");

        dataCadastroProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataCadastroProfActionPerformed(evt);
            }
        });

        jLabel7.setText("Data de nascimento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(userNameCadastroProf, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboboxTurmasCadastroProf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboboxDisciplinssCadastroProf, 0, 382, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSairCadastroProf, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                .addComponent(btnGuardarCadastroProf, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                .addComponent(dataCadastroProf))
                            .addComponent(passwordCadastroProf, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addComponent(jLabel1))
                        .addComponent(nomeCadastroProf, javax.swing.GroupLayout.Alignment.LEADING))
                    .addContainerGap(370, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(15, 15, 15)
                .addComponent(comboboxTurmasCadastroProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboboxDisciplinssCadastroProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userNameCadastroProf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordCadastroProf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataCadastroProf, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarCadastroProf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSairCadastroProf)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(54, 54, 54)
                    .addComponent(nomeCadastroProf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(306, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeCadastroProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCadastroProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCadastroProfActionPerformed

    private void userNameCadastroProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameCadastroProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameCadastroProfActionPerformed

    private void passwordCadastroProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordCadastroProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordCadastroProfActionPerformed

    private void btnGuardarCadastroProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCadastroProfActionPerformed

        if (!userNameCadastroProf.getText().isEmpty() &&
            !passwordCadastroProf.getText().isEmpty() &&
            !dataCadastroProf.getText().isEmpty() &&
            !nomeCadastroProf.getText().isEmpty())
        {
            Turma turma = turmas.get(comboboxTurmasCadastroProf.getSelectedIndex());
            Disc d = turma.getDisc().get(comboboxDisciplinssCadastroProf.getSelectedIndex());
            d.AddProf(new Prof(nomeCadastroProf.getText(), dataCadastroProf.getText(), userNameCadastroProf.getText(), passwordCadastroProf.getText()));
            passwordCadastroProf.setText("");
            nomeCadastroProf.setText("");
            userNameCadastroProf.setText("");
            dataCadastroProf.setText("");
        }
    }//GEN-LAST:event_btnGuardarCadastroProfActionPerformed

    private void btnSairCadastroProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastroProfActionPerformed
        janela.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairCadastroProfActionPerformed

    private void dataCadastroProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataCadastroProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataCadastroProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCadastroProf;
    private javax.swing.JButton btnSairCadastroProf;
    private javax.swing.JComboBox<String> comboboxDisciplinssCadastroProf;
    private javax.swing.JComboBox<String> comboboxTurmasCadastroProf;
    private javax.swing.JTextField dataCadastroProf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeCadastroProf;
    private javax.swing.JTextField passwordCadastroProf;
    private javax.swing.JTextField userNameCadastroProf;
    // End of variables declaration//GEN-END:variables
}
